language: php

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - pwd 
  # Run environmental updates
  - sudo apt-get update > /dev/null
  # Update composer
  - composer selfupdate
  # Configure MySQL for Drupal
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
  # Configure php.ini settings
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  # Install Drush 6
  - composer global require drush/drush:6.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Download Drush Composer extension
  - git clone --branch 8.x-1.x http://git.drupal.org/project/composer.git ~/.drush/composer
  
before_script:
  - drush dl --yes drupal
  - cd drupal-*
  - drush si standard --db-url=mysql://root:@localhost/drupal --yes
  - drush en --yes simpletest
  - drush cc all
  - drush runserver --server=builtin 8080 &
  - sleep 4
  - drush vset --yes simpletest_verbose FALSE

script: drush test-run Syslog --xml --uri=http://127.0.0.1:8080

